CREATE TABLE IF NOT EXISTS "COMPANY" (
    "COMPANY_ID"      INTEGER PRIMARY KEY AUTOINCREMENT,
    "COMPANY_NAME"    TEXT    NOT NULL,
    "CEO_NAME"        TEXT,
    "ADDRESS"         TEXT,
    "COMPANY_EMAIL"   TEXT,
    "COMPANY_PHONE"   TEXT,
    "BUSINESS_NUMBER" TEXT,
    "INDUSTRY"        TEXT,
    "ADMIN_USER_ID"   INTEGER,
    "CREATED_AT"      DATETIME DEFAULT CURRENT_TIMESTAMP,
    "DELETED_AT"      DATETIME
);

CREATE TABLE IF NOT EXISTS "TEAM" (
    "TEAM_ID"    INTEGER PRIMARY KEY AUTOINCREMENT,
    "COMPANY_ID" INTEGER NOT NULL,
    "TEAM_NAME"  TEXT    NOT NULL,
    FOREIGN KEY ("COMPANY_ID") REFERENCES "COMPANY" ("COMPANY_ID")
);

CREATE TABLE IF NOT EXISTS "USER" (
    "USER_ID"       INTEGER PRIMARY KEY AUTOINCREMENT,
    "EMP_NO"        TEXT    NOT NULL,
    "TEAM_ID"       INTEGER,
    "POSITION_NAME" TEXT,
    "USERNAME"      TEXT    NOT NULL,
    "EMAIL"         TEXT    NOT NULL,
    "PHONE"         TEXT,
    "PASSWORD"      TEXT    NOT NULL,
    "JOINED_AT"     DATETIME DEFAULT CURRENT_TIMESTAMP,
    "QUIT_AT"       DATETIME,
    "IS_ADMIN"      INTEGER  DEFAULT 0,
    "CREATED_AT"    DATETIME DEFAULT CURRENT_TIMESTAMP,
    "DELETED_AT"    DATETIME,
    FOREIGN KEY ("TEAM_ID") REFERENCES "TEAM" ("TEAM_ID")
);

CREATE TABLE IF NOT EXISTS "LEAVE" (
    "LEAVE_ID"       INTEGER PRIMARY KEY AUTOINCREMENT,
    "USER_ID"        INTEGER NOT NULL,
    "RELEVANT_YEAR"  INTEGER NOT NULL,
    "LEAVE_TYPE"     TEXT    NOT NULL,
    "TOTAL_DAYS"     REAL    NOT NULL,
    "USED_DAYS"      REAL    NOT NULL,
    "REMAINING_DAYS" REAL    NOT NULL,
    "UPDATED_AT"     DATETIME DEFAULT CURRENT_TIMESTAMP,
    "CREATED_AT"     DATETIME DEFAULT CURRENT_TIMESTAMP,
    "DELETED_AT"     DATETIME,
    FOREIGN KEY ("USER_ID") REFERENCES "USER" ("USER_ID")
);
